#!/usr/bin/perl -w
# $Id:$

use strict;
use warnings;
use Getopt::Long;
use Pod::Usage;
use GTB::File qw(Open);

use NHGRI::SVanalyzer::Comp;

our %Opt;

=head1 NAME

SVbenchmark - compare two VCF files of structural variants, reporting false positive and false negative calls in the test VCF, and precision, recall, and F1 when compared to the "truth" VCF.

=head1 SYNOPSIS

  SVbenchmark --ref <reference FASTA file> --test <VCF-formatted file of test variants> --truth <VCF-formatted file of true variants>
  SVbenchmark --ref <reference FASTA file> --distance_file <distance file produced by previous run> --test <VCF-formatted file of test variants> --truth <VCF-formatted file of true variants>

=head1 DESCRIPTION

The program steps through two VCF files, a "test" file of structural variants to be evaluated and a "truth" file of structural variants which are assumed to be correct. It first writes a distance file of distance metrics between nearby pairs of test and true variants, and then writes VCF files of true positives, false positives, and false negatives, and a summary of recall, precision, and F1 to a summary file.

=cut

#------------
# Begin MAIN 
#------------

process_commandline();

my $ref_fasta = $Opt{ref};
my $test_vcf = $Opt{test};
my $truth_vcf = $Opt{truth};

my $max_distance = $Opt{'max_dist'};

my $prefix = $Opt{'prefix'};
my $output_file = "$prefix.report";
my $workdir = $Opt{'workdir'};

my $output_fh = Open($output_file, "w");

my $rh_distance_matrix;
if ($Opt{'distance_file'}) {
    $rh_distance_matrix = read_distance_file($Opt{'distance_file'});
}
else {
    $rh_distance_matrix = calculate_distance_matrix($test_vcf, $truth_vcf);
}

write_fp_fn_variants($rh_distance_matrix, $test_vcf, $truth_vcf, $output_fh, $prefix );

#------------
# End MAIN
#------------

sub process_commandline {
    # Set defaults here
    %Opt = ( max_dist => 100000, workdir => '.', prefix => 'benchmark' );
    GetOptions(\%Opt, qw( ref=s test=s truth=s max_dist=i prefix=s workdir=s manual help+ version)) || pod2usage(0);
    if ($Opt{manual})  { pod2usage(verbose => 2); }
    if ($Opt{help})    { pod2usage(verbose => $Opt{help}-1); }
    if ($Opt{version}) { die "SVbenchmark.pl, ", q$Revision:$, "\n"; }
    # If non-option arguments are required, uncomment next line
    pod2usage("SVbenchmark --ref <ref fasta> --test <VCF-formatted file of variants to test> --truth <VCF-formatted file of true variants>") if !($Opt{ref} && $Opt{test} && $Opt{truth});
}

sub calculate_distance_matrix {
    my $test_vcf = shift;
    my $truth_vcf = shift;

    my $distance_file = "$prefix.distances";
    my $distance_fh = Open($distance_file, "w");

    print $distance_fh "DIST\tID1\tID2\tAVGALTLENGTH\tALTLENGTHDIFF\tAVGSIZE\tSIZEDIFF\tEDITDIST\tMAXSHIFT\tPOSDIFF\tRELSHIFT\tRELSIZEDIFF\tRELDIST\n";

}

__END__

=head1 OPTIONS

=over 4

=item B<--help|--manual>

Display documentation.  One C<--help> gives a brief synopsis, C<-h -h> shows
all options, C<--manual> provides complete documentation.

=back

=head1 AUTHOR

 Nancy Hansen - nhansen@mail.nih.gov

=head1 LEGAL

This software/database is "United States Government Work" under the terms of
the United States Copyright Act.  It was written as part of the authors'
official duties for the United States Government and thus cannot be
copyrighted.  This software/database is freely available to the public for
use without a copyright notice.  Restrictions cannot be placed on its present
or future use. 

Although all reasonable efforts have been taken to ensure the accuracy and
reliability of the software and data, the National Human Genome Research
Institute (NHGRI) and the U.S. Government does not and cannot warrant the
performance or results that may be obtained by using this software or data.
NHGRI and the U.S.  Government disclaims all warranties as to performance,
merchantability or fitness for any particular purpose. 

In any work or product derived from this material, proper attribution of the
authors as the source of the software or data should be made, using "NHGRI
Genome Technology Branch" as the citation. 

=cut
